name: emit_tooling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - netcdf4
  - multiprocess
  - pyyaml
  - xarray
  - matplotlib
  - rasterio
  - spectral
  - gdal
  - scikit-image
  - pandas
  - geopandas
  - rioxarray
  - s3fs
  - fsspec
  - pip
  - pip:
      - tqdm
  - h5netcdf
  - h5py
  - psutil
  - regex